In [1]:
import numpy as np
import unittest
from Layers import RNN,Initializers
from NeuralNetworkTests import TestFullyConnected
from Optimization import Optimizers
from Layers import Helpers,FullyConnected
class L2Loss:

    def __init__(self):
        self.input_tensor = None

    def forward(self, input_tensor, label_tensor):
        self.input_tensor = input_tensor
        return np.sum(np.square(input_tensor - label_tensor))

    def backward(self, label_tensor):
        return 2*np.subtract(self.input_tensor, label_tensor)
class TestRNN(unittest.TestCase):
    def setUp(self):
        self.batch_size = 9
        self.input_size = 13
        self.output_size = 5
        self.hidden_size = 7
        self.input_tensor = np.random.rand(self.input_size, self.batch_size).T

        self.categories = 4
        self.label_tensor = np.zeros([self.categories, self.batch_size]).T
        for i in range(self.batch_size):
            self.label_tensor[i, np.random.randint(0, self.categories)] = 1
    def test_gradient(self):
        input_tensor = np.abs(np.random.random((self.input_size, self.batch_size))).T
        layers = list()
        layer = RNN.RNN(self.input_size, self.hidden_size, self.categories)
        layer.initialize(Initializers.He(), Initializers.He())
        layers.append(layer)
        layers.append(L2Loss())
        difference = Helpers.gradient_check(layers, input_tensor, self.label_tensor)
        print(np.sum(difference), 1e-4)
    def test_gradient_weights(self):
        input_tensor = np.abs(np.random.random((self.input_size, self.batch_size))).T
        layers = list()
        layer = RNN.RNN(self.input_size, self.hidden_size, self.categories)
        layer.initialize(Initializers.He(), Initializers.He())
        layers.append(layer)
        layers.append(L2Loss())
        difference = Helpers.gradient_check_weights(layers, input_tensor, self.label_tensor, False)
        print(np.sum(difference), 1e-4)
t1 = TestRNN()
t1.setUp()
t1.test_gradient()
t1.test_gradient_weights()

ValueError: could not broadcast input array from shape (14,) into shape (13,)

In [3]:
n1= np.random.random([1,7])
n2 = np.random.random([7,5])
np.dot(n1,n2).shape

(1, 5)

(2, 3)
[[1 2 3]
 [1 2 3]]


array([[1, 2],
       [3, 1],
       [2, 3]])