In [ ]:
import Layers.FullyConnected as fc
fn = fc(10,20)


In [27]:
import numpy as np
m102= np.random.uniform(0,1,(7,10))
m510 = np.random.uniform(0,1,(5,7))
m102.shape

(7, 10)

In [24]:
import numpy as np
from Optimization import Optimizers
class BaseLayer:
    def __init__(self,trainable=False,weight=None):
        self.trainable = trainable
        self.weights = weight

 
class FullyConnected(BaseLayer):
    def __init__(self,input_size,output_size):
        super().__init__(True,np.random.uniform(0,1,(input_size+1,output_size))) #weights + bias
        self.grad_weights = None
        self._optimizer = None
    def set_optimizer(self,optimizer):
        self._optimizer = optimizer
    def get_optimizer(self):
        return self._optimizer
    def forward(self,input_tensor):
        '''
            input shape : (bs,input_size) 
            weights shape :(input_size , output_size)
            bias shape:(1,output_size)
            input * weight + bias = (bs,input_size)*(input_size,output_size)+(1,output_size)
            return (bs,output_size)
        '''
        self.input_tensor = input_tensor
        return np.dot(input_tensor,self.weights[:-1,:])+self.weights[-1:,:]
    def backward(self,error_tensor):
        '''
            &L/&W = self.input_tensor.T(inputsize,bs) * erro_tensor(bs,outsize) =(inputsize,outsize)
            &L/&b = error_tensor.sum to (1,outsize)
        '''
        self.grad_weights = np.dot(self.input_tensor.T , error_tensor)
        self.grad_bias = np.sum(error_tensor ,axis=0)
        self._optimizer.calculate_update(self.weights[:-1,:],self.grad_weights)
        self._optimizer.calculate_update(self.weights[-1:,:],self.grad_bias)
f1 = FullyConnected(10,20)
f1.optimizer = Optimizers.Sgd(1)

In [30]:
batch_size = 9
input_size = 4
output_size = 3
input_tensor = np.random.rand(batch_size, input_size)
layer = FullyConnected(input_size, output_size)
layer.set_optimizer(Optimizers.Sgd(1))

output_tensor = layer.forward(input_tensor)
error_tensor = np.zeros([batch_size, output_size])
error_tensor -= output_tensor
            # print(error_tensor.shape)
layer.backward(error_tensor)
new_output_tensor = layer.forward(input_tensor)
print(np.sum(np.power(output_tensor, 2)))
print(np.sum(np.power(new_output_tensor, 2)))

51.42762299797902
51.42762299797902


In [44]:
c=np.random.random((2,4))
c[1,1]=-1
print(c)
print(c * (c >0).astype(float))

[[ 0.29977113  0.96987881  0.70923767  0.65452177]
 [ 0.93262138 -1.          0.87956377  0.79573793]]
[[ 0.29977113  0.96987881  0.70923767  0.65452177]
 [ 0.93262138 -0.          0.87956377  0.79573793]]


In [13]:
import numpy as np

# 模拟 logits 和真实标签
logits = np.array([[2.0, 1.0, 0.1], [0.5, 2.1, 0.3]])  # (N, C) 形状
y_true = np.array([0, 1])  # 真实标签索引 (N,)

# One-Hot 编码
num_classes = logits.shape[1]
y_onehot = np.eye(num_classes)[y_true]

# Softmax 前向传播
exp_logits = np.exp(logits - np.max(logits, axis=1, keepdims=True))  # 稳定 Softmax
softmax = exp_logits / np.sum(exp_logits, axis=1, keepdims=True)

# 交叉熵损失
loss = -np.sum(y_onehot * np.log(softmax)) / logits.shape[0]

# 反向传播：损失对 logits 的梯度
grad_logits = (softmax - y_onehot) / logits.shape[0]

# 输出结果
print("Softmax 概率分布:\n", softmax)
print("交叉熵损失值:", loss)
print("损失对 logits 的梯度:\n", grad_logits)


Softmax 概率分布:
 [[0.65900114 0.24243297 0.09856589]
 [0.14767203 0.73142434 0.12090363]]
交叉熵损失值: 0.3648957545487306
损失对 logits 的梯度:
 [[-0.17049943  0.12121649  0.04928295]
 [ 0.07383601 -0.13428783  0.06045182]]


In [2]:
import numpy as np
categories=4
batch_size=9
label_tensor = np.zeros([batch_size, categories])
print(label_tensor)
for i in range(batch_size):
    label_tensor[i, np.random.randint(0, categories)] = 1
print(label_tensor)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
x1=np.array([1,1,0,0,1])
x2=np.array([1,1,1,1,1])
x1[x2]

array([1, 1, 1, 1, 1])

In [2]:
from Layers import *
data_layer=Helpers.IrisData(50)
inpu,la = data_layer.next()
print(inpu.shape)
print(la.shape)

(50, 4)
(50, 3)


In [5]:
from Layers.Base import BaseLayer
import numpy as np
b1 = BaseLayer(True, np.random.uniform(0, 1, (5, 10)))
print(b1.trainable)
print(b1.weights)

True
[[0.95853426 0.52767175 0.34233081 0.23615943 0.95853473 0.69945299
  0.04639071 0.9918899  0.68529956 0.45551153]
 [0.79932413 0.46298366 0.086053   0.45836218 0.66441642 0.95435384
  0.12149753 0.9303957  0.35823565 0.69545343]
 [0.63786152 0.10540237 0.0837914  0.21325733 0.12651872 0.5958658
  0.7694232  0.09080234 0.39702149 0.84720904]
 [0.50257649 0.85657757 0.77369515 0.15300915 0.70269489 0.1470951
  0.7802047  0.01999168 0.83133624 0.86435769]
 [0.48247934 0.63253051 0.62734556 0.15544277 0.88046778 0.15380405
  0.77569244 0.8935717  0.24370536 0.63791389]]
